### ISSUE TITLE
Breaks with new getDefaultProps behavior

### ISSUE THREAD

**Issue by stereosteve** [prometheusresearch/react-selectbox#2]
`getDefaultProps` is evaluated immediately at declaration time as of React 0.11.  Since `Result` is declared after `Results` the default renderer is undefined.

[Here is a quick fix](https://github.com/stereosteve/react-autocomplete/commit/fd4db0a79db7128cb75687b0393217f204c46f93), but you could also move `Result` definition above `Results` or put in a separate file.  I can make a pull request if you want.

**Comment by andreypopp** [comment]
Fixed.
